INSERT INTO accounts (account_id, first_name, last_name, address, undertaking, business_unit) VALUES
(100075, 'Alex', 'Smith', '76 Power Lane, Cityville', 'Ijaiye', 'Abule Egba'),
(100076, 'Taylor', 'Johnson', '77 Power Lane, Cityville', 'Akute', 'Abule Egba'),
(100077, 'Jordan', 'Williams', '78 Power Lane, Cityville', 'Iju', 'Abule Egba'),
(100078, 'Morgan', 'Brown', '79 Power Lane, Cityville', 'Dopemu', 'Akowonjo'),
(100079, 'Casey', 'Jones', '80 Power Lane, Cityville', 'Egbeda', 'Akowonjo'),
(100080, 'Riley', 'Garcia', '81 Power Lane, Cityville', 'Ipaja', 'Akowonjo'),
(100081, 'Jamie', 'Miller', '82 Power Lane, Cityville', 'Idimu', 'Akowonjo'),
(100082, 'Avery', 'Davis', '83 Power Lane, Cityville', 'PTC', 'Ikeja'),
(100083, 'Peyton', 'Martinez', '84 Power Lane, Cityville', 'Ifako', 'Ikeja'),
(100084, 'Quinn', 'Hernandez', '85 Power Lane, Cityville', 'Oregun', 'Ikeja'),
(100085, 'Harper', 'Lopez', '86 Power Lane, Cityville', 'Oba-Akran', 'Ikeja'),
(100086, 'Reese', 'Gonzalez', '87 Power Lane, Cityville', 'Epe', 'Ikorodu'),
(100087, 'Skyler', 'Wilson', '88 Power Lane, Cityville', 'Odogunyan', 'Ikorodu'),
(100088, 'Rowan', 'Anderson', '89 Power Lane, Cityville', 'Adiyan', 'Ikorodu'),
(100089, 'Sawyer', 'Thomas', '90 Power Lane, Cityville', 'Ketu', 'Shomolu'),
(100090, 'Emerson', 'Taylor', '91 Power Lane, Cityville', 'Magodo', 'Shomolu'),
(100091, 'Finley', 'Moore', '92 Power Lane, Cityville', 'Ilupeju', 'Shomolu'),
(100092, 'Dakota', 'Jackson', '93 Power Lane, Cityville', 'GRA', 'Shomolu'),
(100093, 'Elliot', 'Martin', '94 Power Lane, Cityville', 'Ijegun', 'Oshodi'),
(100094, 'Hayden', 'Lee', '95 Power Lane, Cityville', 'Ikotun', 'Oshodi'),
(100095, 'Jesse', 'Perez', '96 Power Lane, Cityville', 'Igando', 'Oshodi'),
(100096, 'Kendall', 'Thompson', '97 Power Lane, Cityville', 'Oke-Afa', 'Oshodi'),
(100097, 'Logan', 'White', '98 Power Lane, Cityville', 'Ijaiye', 'Abule Egba'),
(100098, 'Parker', 'Harris', '99 Power Lane, Cityville', 'Akute', 'Abule Egba'),
(100099, 'Remy', 'Sanchez', '100 Power Lane, Cityville', 'Iju', 'Abule Egba'),
